#server:
#  address:     ":8000"
#  openapiPath: "/api.json"
#  swaggerPath: "/swagger"
#
#logger:
#  level : "all"
#  stdout: true
server:
  address: ":30300"
  serverRoot: "resource/public"
  dumpRouterMap: false
  routeOverWrite: true
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  NameToUriType: 3
  maxHeaderBytes: "20KB"
  clientMaxBodySize: "300MB"
  # Logging配置
  logPath: "resource/log/server"                 # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  logStdout: true               # 日志是否输出到终端。默认为true
  errorStack: true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
  errorLogEnabled: true               # 是否记录异常日志信息到日志中。默认为true
  errorLogPattern: "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
  accessLogEnabled: true              # 是否记录访问日志。默认为false
  accessLogPattern: "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"

logger:
  path: "resource/log/run"
  file: "{Y-m-d}.log"
  level: "all"
  stdout: true



# Database.
database:
  default:
    # 42.193.247.183
    # 127.0.0.1
    link: "mysql:root:JyMysql@007@tcp(42.193.247.183:3306)/tender?charset=utf8mb4&parseTime=true&loc=Local"
    debug: true
    charset: "utf8mb4" #数据库编码
    dryRun: false #空跑
    maxIdle: 10 #连接池最大闲置的连接数
    maxOpen: 10 #连接池最大打开的连接数
    maxLifetime: "30s" #(单位秒)连接对象可重复使用的时间长度
  data:
    # 81.71.49.57
    # 172.16.0.17
    link: "mysql:root:JyMysql@007@tcp(81.71.49.57:3306)/crawldata?charset=utf8mb4&parseTime=true"
    debug: true
    charset: "utf8mb4" #数据库编码
    dryRun: false #空跑
    maxIdle: 10 #连接池最大闲置的连接数
    maxOpen: 10 #连接池最大打开的连接数
    maxLifetime: "30s" #(单位秒)连接对象可重复使用的时间长度
  logger:
    level: "all"
    stdout: true
    #Path: "resource/log/sql"

gfToken:
  cacheKey: "gfToken:"
  timeOut: 604800
  maxRefresh: 432000
  multiLogin: true
  encryptKey: "49c54195e750b04e74a8429b17896586"
  cacheModel: "redis"
  # 设置不拦截地址
  excludePaths:
    - "/api/v1/system/login"
    - "/api/v1/desk/login"
#DeskToken:
#  cacheKey: "DeskToken:"
#  timeOut: 10800
#  maxRefresh: 5400
#  multiLogin: true
#  encryptKey: "49c54195e750b04e74a8429b17896586"
#  cacheModel: "redis"
#  # 设置不拦截地址
#  excludePaths:
#    - "/api/v1/desk/login"


# Redis 配置示例
redis:
  # 单实例配置
  # asimov@77
  default:
    # address: 42.193.247.183:6379
    address: 42.193.247.183:6379
    pass: asimov@77
    db: 1
    idleTimeout: "60s" #连接最大空闲时间，使用时间字符串例如30s/1m/1d
    maxConnLifetime: "90s" #连接最长存活时间，使用时间字符串例如30s/1m/1d
    waitTimeout: "60s" #等待连接池连接的超时时间，使用时间字符串例如30s/1m/1d
    dialTimeout: "30s" #TCP连接的超时时间，使用时间字符串例如30s/1m/1d
    readTimeout: "30s" #TCP的Read操作超时时间，使用时间字符串例如30s/1m/1d
    writeTimeout: "30s" #TCP的Write操作超时时间，使用时间字符串例如30s/1m/1d
    maxActive: 100

# 配置后台权限id
system:
  notCheckAuthAdminIds: [ 1 ]  #无需验证后台权限的用户id
  dataDir: "./resource/data"
  cache:
    model: "redis"  #缓存模式 memory OR redis
    prefix: "Tender:" #缓存前缀

#casbin配置
casbin:
  modelFile: "./resource/casbin/rbac_model.conf"
  policyFile: "./resource/casbin/rbac_policy.csv"

mp:
  wxappid: "wxd57537f1f1743ba4"
  wxappsecret: "1b4c6f284e7bd1dde15c11daba1be81c"
  token: "cloud"
pay:
  notifyUrlHost: "https://biaoziku.com"

zinc: # Zinc搜索配置
  host: "http://42.193.247.183:4080/"
  index: "zhaobiao-data"
  user: "admin"
  password: "Complexpass#123"
  secure: False
bdzinc: # bdZinc搜索配置
  host: "http://81.71.49.57:4080/"
  index: "crawler"
  user: "asimov"
  password: "asimov@77"
  secure: False