// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/system/dao/internal"
)

// internalBiddingInformationDao is internal type for wrapping internal DAO implements.
type internalBiddingInformationDao = *internal.BiddingInformationDao

// biddingInformationDao is the data access object for table bidding_information.
// You can define custom methods on it to extend its functionality as you wish.
type biddingInformationDao struct {
	internalBiddingInformationDao
}

var (
	// BiddingInformation is globally public accessible object for table bidding_information operations.
	BiddingInformation = biddingInformationDao{
		internal.NewBiddingInformationDao(),
	}
)

// Fill with you ideas below.
