// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/system/dao/internal"
)

// internalMemberUserDao is internal type for wrapping internal DAO implements.
type internalMemberUserDao = *internal.MemberUserDao

// memberUserDao is the data access object for table member_user.
// You can define custom methods on it to extend its functionality as you wish.
type memberUserDao struct {
	internalMemberUserDao
}

var (
	// MemberUser is globally public accessible object for table member_user operations.
	MemberUser = memberUserDao{
		internal.NewMemberUserDao(),
	}
)

// Fill with you ideas below.
