// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/system/dao/internal"
)

// internalMemberIntegralDao is internal type for wrapping internal DAO implements.
type internalMemberIntegralDao = *internal.MemberIntegralDao

// memberIntegralDao is the data access object for table member_integral.
// You can define custom methods on it to extend its functionality as you wish.
type memberIntegralDao struct {
	internalMemberIntegralDao
}

var (
	// MemberIntegral is globally public accessible object for table member_integral operations.
	MemberIntegral = memberIntegralDao{
		internal.NewMemberIntegralDao(),
	}
)

// Fill with you ideas below.
