// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/system/dao/internal"
)

// internalMemberManagementDao is internal type for wrapping internal DAO implements.
type internalMemberManagementDao = *internal.MemberManagementDao

// memberManagementDao is the data access object for table member_management.
// You can define custom methods on it to extend its functionality as you wish.
type memberManagementDao struct {
	internalMemberManagementDao
}

var (
	// MemberManagement is globally public accessible object for table member_management operations.
	MemberManagement = memberManagementDao{
		internal.NewMemberManagementDao(),
	}
)

// Fill with you ideas below.
