// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/system/dao/internal"
)

// internalPaySettingsDao is internal type for wrapping internal DAO implements.
type internalPaySettingsDao = *internal.PaySettingsDao

// paySettingsDao is the data access object for table pay_settings.
// You can define custom methods on it to extend its functionality as you wish.
type paySettingsDao struct {
	internalPaySettingsDao
}

var (
	// PaySettings is globally public accessible object for table pay_settings operations.
	PaySettings = paySettingsDao{
		internal.NewPaySettingsDao(),
	}
)

// Fill with you ideas below.
