// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/system/dao/internal"
)

// internalSysWxQrcodeDao is internal type for wrapping internal DAO implements.
type internalSysWxQrcodeDao = *internal.SysWxQrcodeDao

// sysWxQrcodeDao is the data access object for table sys_wx_qrcode.
// You can define custom methods on it to extend its functionality as you wish.
type sysWxQrcodeDao struct {
	internalSysWxQrcodeDao
}

var (
	// SysWxQrcode is globally public accessible object for table sys_wx_qrcode operations.
	SysWxQrcode = sysWxQrcodeDao{
		internal.NewSysWxQrcodeDao(),
	}
)

// Fill with you ideas below.
