// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/system/dao/internal"
)

// internalSysWxUserDao is internal type for wrapping internal DAO implements.
type internalSysWxUserDao = *internal.SysWxUserDao

// sysWxUserDao is the data access object for table sys_wx_user.
// You can define custom methods on it to extend its functionality as you wish.
type sysWxUserDao struct {
	internalSysWxUserDao
}

var (
	// SysWxUser is globally public accessible object for table sys_wx_user operations.
	SysWxUser = sysWxUserDao{
		internal.NewSysWxUserDao(),
	}
)

// Fill with you ideas below.
