// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/system/dao/internal"
)

// internalSysWsMsgDao is internal type for wrapping internal DAO implements.
type internalSysWsMsgDao = *internal.SysWsMsgDao

// sysWsMsgDao is the data access object for table sys_ws_msg.
// You can define custom methods on it to extend its functionality as you wish.
type sysWsMsgDao struct {
	internalSysWsMsgDao
}

var (
	// SysWsMsg is globally public accessible object for table sys_ws_msg operations.
	SysWsMsg = sysWsMsgDao{
		internal.NewSysWsMsgDao(),
	}
)

// Fill with you ideas below.
