// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Law is the golang structure for table law.
type Law struct {
	Id      int64  `json:"id"      description:"UID"`
	Fileid  string `json:"fileid"  description:"文件id"`
	Publish string `json:"publish" description:"公布日期"`
	Expiry  string `json:"expiry"  description:"施行日期"`
	Office  string `json:"office"  description:"制定机关"`
	Title   string `json:"title"   description:"标题"`
	Type    string `json:"type"    description:"类型"`
	Word    string `json:"word"    description:"word"`
	Pdf     string `json:"pdf"     description:"pdf"`
	Url     string `json:"url"     description:"外部链接"`
}
