// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MemberIntegral is the golang structure for table member_integral.
type MemberIntegral struct {
	Id                  uint64 `json:"id"                  description:""`
	MonthlycardIntegral int    `json:"monthlycardIntegral" description:"月卡积分"`
	QuartercardIntegral int    `json:"quartercardIntegral" description:"季卡积分"`
	AnnualcardIntegral  int    `json:"annualcardIntegral"  description:"年卡积分"`
	KnowledgeIntegral   int    `json:"knowledgeIntegral"   description:"发布知识积分"`
	VideoIntegral       int    `json:"videoIntegral"       description:"发布视频积分"`
	IssueIntegral       int    `json:"issueIntegral"       description:"发行积分"`
	Ordinary            int    `json:"ordinary"            description:"普通"`
	Select              int    `json:"select"              description:"精选"`
	Ratio               int    `json:"ratio"               description:"普通积分比例"`
	MonthlycardRatio    int    `json:"monthlycardRatio"    description:"月卡积分比例"`
	QuartercardRatio    int    `json:"quartercardRatio"    description:"季卡积分比例"`
	AnnualcardRatio     int    `json:"annualcardRatio"     description:"年卡积分比例"`
}
