// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MemberFee is the golang structure for table member_fee.
type MemberFee struct {
	Id                  uint64 `json:"id"                  description:""`
	MonthlycardOriginal string `json:"monthlycardOriginal" description:"月卡原价"`
	MonthlycardCurrent  string `json:"monthlycardCurrent"  description:"月卡现价"`
	QuartercardOriginal string `json:"quartercardOriginal" description:"季卡原价"`
	QuartercardCurrent  string `json:"quartercardCurrent"  description:"季卡现价"`
	AnnualcardOriginal  string `json:"annualcardOriginal"  description:"年卡原价"`
	AnnualcardCurrent   string `json:"annualcardCurrent"   description:"年卡现价"`
	DownloadKnowledge   string `json:"downloadKnowledge"   description:"下载知识"`
	DownloadVideo       string `json:"downloadVideo"       description:"下载视频"`
}
