// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// PaySettings is the golang structure for table pay_settings.
type PaySettings struct {
	Id                     int    `json:"id"                     description:""`
	WeixinMchid            string `json:"weixinMchid"            description:""`
	WeixinAppid            string `json:"weixinAppid"            description:""`
	WeixinApikey           string `json:"weixinApikey"           description:""`
	WeixinSerialno         string `json:"weixinSerialno"         description:""`
	WeixinPrivatekey       string `json:"weixinPrivatekey"       description:""`
	AlipayAppid            string `json:"alipayAppid"            description:""`
	AlipayPrivatekey       string `json:"alipayPrivatekey"       description:""`
	AlipayAppCertPublicKey string `json:"alipayAppCertPublicKey" description:""`
	AlipayRootCert         string `json:"alipayRootCert"         description:""`
	AlipayPublicCert       string `json:"alipayPublicCert"       description:""`
}
