// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PurchaseLog is the golang structure for table purchase_log.
type PurchaseLog struct {
	Id        int         `json:"id"        description:""`
	NickName  string      `json:"nickName"  description:""`
	Mobile    string      `json:"mobile"    description:""`
	UserId    int         `json:"userId"    description:""`
	Memo      string      `json:"memo"      description:""`
	Amount    int         `json:"amount"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
	DeletedAt *gtime.Time `json:"deletedAt" description:""`
	TargetId  int         `json:"targetId"  description:""`
	UserName  string      `json:"userName"  description:""`
	PayType   string      `json:"payType"   description:"支付类型"`
	OrderNo   string      `json:"orderNo"   description:"订单号"`
}
