// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysWsMsg is the golang structure for table sys_ws_msg.
type SysWsMsg struct {
	Id        uint        `json:"id"        description:""`
	MessageId string      `json:"messageId" description:""`
	UserId    uint        `json:"userId"    description:""`
	Content   string      `json:"content"   description:""`
	IsRead    uint        `json:"isRead"    description:""`
	IsDel     uint        `json:"isDel"     description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
