// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysEnterprise is the golang structure for table sys_enterprise.
type SysEnterprise struct {
	Id                   uint        `json:"id"                   description:""`
	Name                 string      `json:"name"                 description:"企业名称"`
	Location             string      `json:"location"             description:"所在地"`
	Industry             string      `json:"industry"             description:"所属行业"`
	Contact              string      `json:"contact"              description:"联系电话"`
	Icon                 string      `json:"icon"                 description:"图标"`
	Introduction         string      `json:"introduction"         description:"简介"`
	Remark               string      `json:"remark"               description:"其他"`
	License              string      `json:"license"              description:"营业执照"`
	LicenseStatus        uint        `json:"licenseStatus"        description:"审核状态 0待审核 1审核通过 2审核未通过"`
	Certificate          string      `json:"certificate"          description:"证明书"`
	CertificateStatus    uint        `json:"certificateStatus"    description:"审核状态 0待审核 1审核通过 2审核未通过"`
	OperationId          int64       `json:"operationId"          description:"操作管理员id"`
	EstablishmentAt      string      `json:"establishmentAt"      description:"成立时间"`
	CreatedAt            *gtime.Time `json:"createdAt"            description:"创建日期"`
	UpdatedAt            *gtime.Time `json:"updatedAt"            description:"修改日期"`
	LicenseMessage       string      `json:"licenseMessage"       description:"营业执照审核留言"`
	CertificateMessage   string      `json:"certificateMessage"   description:"证明书审核留言"`
	UserId               uint        `json:"userId"               description:"用户id"`
	Nickname             string      `json:"nickname"             description:"企业简称"`
	Content              string      `json:"content"              description:"主页内容"`
	OplicenseMessage     string      `json:"oplicenseMessage"     description:"营业执照管理员留言"`
	OpcertificateMessage string      `json:"opcertificateMessage" description:"证明书管理员留言"`
}
