// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysWxUser is the golang structure for table sys_wx_user.
type SysWxUser struct {
	Id        uint        `json:"id"        description:""`
	MainId    uint        `json:"mainId"    description:""`
	OpenId    string      `json:"openId"    description:""`
	UnionId   string      `json:"unionId"   description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
