// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysWxQrcode is the golang structure for table sys_wx_qrcode.
type SysWxQrcode struct {
	Id        uint        `json:"id"        description:""`
	SenceId   string      `json:"senceId"   description:""`
	IsScan    int         `json:"isScan"    description:""`
	Token     string      `json:"token"     description:""`
	OpenId    string      `json:"openId"    description:""`
	CreatedAt *gtime.Time `json:"createdAt" description:""`
	UpdatedAt *gtime.Time `json:"updatedAt" description:""`
}
