// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// BiddingInformation is the golang structure of table bidding_information for DAO operations like Where/Data.
type BiddingInformation struct {
	g.Meta                 `orm:"table:bidding_information, do:true"`
	Id                     interface{} // UID
	BulletinType           interface{} // 公告类型
	NoticeNature           interface{} // 公告性质
	City                   interface{} // 所属城市
	IndustryClassification interface{} // 行业分类
	ReleaseTime            interface{} // 发布时间
	TenderDeadline         interface{} // 投标截止时间
	BidopeningTime         interface{} // 开标时间
	Title                  interface{} // 标题
	AnnouncementContent    interface{} // 公告内容
	Attachment             interface{} // 招标附件
	Amount                 interface{} // 金额
	ContactPerson          interface{} // 联系人
	ContactInformation     interface{} // 联系方式
	ContactContent         interface{} // 联系方式内容
	Link                   interface{} // 源链接
}
