// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Law is the golang structure of table law for DAO operations like Where/Data.
type Law struct {
	g.Meta  `orm:"table:law, do:true"`
	Id      interface{} // UID
	Fileid  interface{} // 文件id
	Publish interface{} // 公布日期
	Expiry  interface{} // 施行日期
	Office  interface{} // 制定机关
	Title   interface{} // 标题
	Type    interface{} // 类型
	Word    interface{} // word
	Pdf     interface{} // pdf
	Url     interface{} // 外部链接
}
