// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MemberIntegral is the golang structure of table member_integral for DAO operations like Where/Data.
type MemberIntegral struct {
	g.Meta              `orm:"table:member_integral, do:true"`
	Id                  interface{} //
	MonthlycardIntegral interface{} // 月卡积分
	QuartercardIntegral interface{} // 季卡积分
	AnnualcardIntegral  interface{} // 年卡积分
	KnowledgeIntegral   interface{} // 发布知识积分
	VideoIntegral       interface{} // 发布视频积分
	IssueIntegral       interface{} // 发行积分
	Ordinary            interface{} // 普通
	Select              interface{} // 精选
	Ratio               interface{} // 普通积分比例
	MonthlycardRatio    interface{} // 月卡积分比例
	QuartercardRatio    interface{} // 季卡积分比例
	AnnualcardRatio     interface{} // 年卡积分比例
}
