// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// PaySettings is the golang structure of table pay_settings for DAO operations like Where/Data.
type PaySettings struct {
	g.Meta                 `orm:"table:pay_settings, do:true"`
	Id                     interface{} //
	WeixinMchid            interface{} //
	WeixinAppid            interface{} //
	WeixinApikey           interface{} //
	WeixinSerialno         interface{} //
	WeixinPrivatekey       interface{} //
	AlipayAppid            interface{} //
	AlipayPrivatekey       interface{} //
	AlipayAppCertPublicKey interface{} //
	AlipayRootCert         interface{} //
	AlipayPublicCert       interface{} //
}
