// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PurchaseLog is the golang structure of table purchase_log for DAO operations like Where/Data.
type PurchaseLog struct {
	g.Meta    `orm:"table:purchase_log, do:true"`
	Id        interface{} //
	NickName  interface{} //
	Mobile    interface{} //
	UserId    interface{} //
	Memo      interface{} //
	Amount    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
	TargetId  interface{} //
	UserName  interface{} //
	PayType   interface{} // 支付类型
	OrderNo   interface{} // 订单号
}
