// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysWxUser is the golang structure of table sys_wx_user for DAO operations like Where/Data.
type SysWxUser struct {
	g.Meta    `orm:"table:sys_wx_user, do:true"`
	Id        interface{} //
	MainId    interface{} //
	OpenId    interface{} //
	UnionId   interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
