// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysEnterprise is the golang structure of table sys_enterprise for DAO operations like Where/Data.
type SysEnterprise struct {
	g.Meta               `orm:"table:sys_enterprise, do:true"`
	Id                   interface{} //
	Name                 interface{} // 企业名称
	Location             interface{} // 所在地
	Industry             interface{} // 所属行业
	Contact              interface{} // 联系电话
	Icon                 interface{} // 图标
	Introduction         interface{} // 简介
	Remark               interface{} // 其他
	License              interface{} // 营业执照
	LicenseStatus        interface{} // 审核状态 0待审核 1审核通过 2审核未通过
	Certificate          interface{} // 证明书
	CertificateStatus    interface{} // 审核状态 0待审核 1审核通过 2审核未通过
	OperationId          interface{} // 操作管理员id
	EstablishmentAt      interface{} // 成立时间
	CreatedAt            *gtime.Time // 创建日期
	UpdatedAt            *gtime.Time // 修改日期
	LicenseMessage       interface{} // 营业执照审核留言
	CertificateMessage   interface{} // 证明书审核留言
	UserId               interface{} // 用户id
	Nickname             interface{} // 企业简称
	Content              interface{} // 主页内容
	OplicenseMessage     interface{} // 营业执照管理员留言
	OpcertificateMessage interface{} // 证明书管理员留言
}
