// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysWxQrcode is the golang structure of table sys_wx_qrcode for DAO operations like Where/Data.
type SysWxQrcode struct {
	g.Meta    `orm:"table:sys_wx_qrcode, do:true"`
	Id        interface{} //
	SenceId   interface{} //
	IsScan    interface{} //
	Token     interface{} //
	OpenId    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
