// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysWsMsg is the golang structure of table sys_ws_msg for DAO operations like Where/Data.
type SysWsMsg struct {
	g.Meta    `orm:"table:sys_ws_msg, do:true"`
	Id        interface{} //
	MessageId interface{} //
	UserId    interface{} //
	Content   interface{} //
	IsRead    interface{} //
	IsDel     interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
