// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ConsultationDao is the data access object for table consultation.
type ConsultationDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns ConsultationColumns // columns contains all the column names of Table for convenient usage.
}

// ConsultationColumns defines and stores column names for table consultation.
type ConsultationColumns struct {
	Id           string //
	Type         string // 类型
	Title        string // 标题
	Content      string // 内容
	Publish      string // 发布日期
	Expiry       string // 施行日期
	Office       string // 制定机关
	Url          string // 外部链接
	Attachment   string // 附件
	CreatedAt    string // 创建时间
	Source       string // 来源
	Status       string // 0 无效,1 有效 时效性
	Display      string // 是否展示,0不展示1展示
	Height       string // 0高1中2低
	Rank         string // 排序
	Site         string // 来源
	OriginalType string // 原始类型
	Crawler      string // 是否爬取,0 非爬取 1 爬取
}

//  consultationColumns holds the columns for table consultation.
var consultationColumns = ConsultationColumns{
	Id:           "id",
	Type:         "type",
	Title:        "title",
	Content:      "content",
	Publish:      "publish",
	Expiry:       "expiry",
	Office:       "office",
	Url:          "url",
	Attachment:   "attachment",
	CreatedAt:    "created_at",
	Source:       "source",
	Status:       "status",
	Display:      "display",
	Height:       "height",
	Rank:         "rank",
	Site:         "site",
	OriginalType: "original_type",
	Crawler:      "crawler",
}

// NewConsultationDao creates and returns a new DAO object for table data access.
func NewConsultationDao() *ConsultationDao {
	return &ConsultationDao{
		group:   "default",
		table:   "consultation",
		columns: consultationColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ConsultationDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ConsultationDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ConsultationDao) Columns() ConsultationColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ConsultationDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ConsultationDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ConsultationDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
