// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// HisKnowledgeDao is the data access object for table his_knowledge.
type HisKnowledgeDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns HisKnowledgeColumns // columns contains all the column names of Table for convenient usage.
}

// HisKnowledgeColumns defines and stores column names for table his_knowledge.
type HisKnowledgeColumns struct {
	Id          string //
	KnowledgeId string // 知识id
	UserId      string // 用户id
	CreatedAt   string // 发布时间
	UpdatedAt   string // 更新时间
	DeletedAt   string // 删除时间
}

//  hisKnowledgeColumns holds the columns for table his_knowledge.
var hisKnowledgeColumns = HisKnowledgeColumns{
	Id:          "id",
	KnowledgeId: "knowledge_id",
	UserId:      "user_id",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
	DeletedAt:   "deleted_at",
}

// NewHisKnowledgeDao creates and returns a new DAO object for table data access.
func NewHisKnowledgeDao() *HisKnowledgeDao {
	return &HisKnowledgeDao{
		group:   "default",
		table:   "his_knowledge",
		columns: hisKnowledgeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *HisKnowledgeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *HisKnowledgeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *HisKnowledgeDao) Columns() HisKnowledgeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *HisKnowledgeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *HisKnowledgeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *HisKnowledgeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
