// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MemberSubscribeDao is the data access object for table member_subscribe.
type MemberSubscribeDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns MemberSubscribeColumns // columns contains all the column names of Table for convenient usage.
}

// MemberSubscribeColumns defines and stores column names for table member_subscribe.
type MemberSubscribeColumns struct {
	Id        string //
	Name      string // 方案名称
	Type      string // 信息类型
	Location  string // 所在地
	Keywords  string // 关键字
	UserId    string // 用户id
	CreatedAt string // 收藏时间
	UpdatedAt string // 更新时间
	DeletedAt string // 删除时间
	Industry  string // 行业类型
}

//  memberSubscribeColumns holds the columns for table member_subscribe.
var memberSubscribeColumns = MemberSubscribeColumns{
	Id:        "id",
	Name:      "name",
	Type:      "type",
	Location:  "location",
	Keywords:  "keywords",
	UserId:    "user_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	Industry:  "industry",
}

// NewMemberSubscribeDao creates and returns a new DAO object for table data access.
func NewMemberSubscribeDao() *MemberSubscribeDao {
	return &MemberSubscribeDao{
		group:   "default",
		table:   "member_subscribe",
		columns: memberSubscribeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MemberSubscribeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MemberSubscribeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MemberSubscribeDao) Columns() MemberSubscribeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MemberSubscribeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MemberSubscribeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MemberSubscribeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
