// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// RechargeOrderDao is the data access object for table recharge_order.
type RechargeOrderDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns RechargeOrderColumns // columns contains all the column names of Table for convenient usage.
}

// RechargeOrderColumns defines and stores column names for table recharge_order.
type RechargeOrderColumns struct {
	Id             string //
	Type           string //
	UserId         string //
	OriginalAmount string //
	PayAmount      string //
	Status         string //
	PayType        string //
	Memo           string //
	CreatedAt      string //
	UpdatedAt      string //
	DeletedAt      string //
	PayTime        string //
	OrderNo        string //
}

// rechargeOrderColumns holds the columns for table recharge_order.
var rechargeOrderColumns = RechargeOrderColumns{
	Id:             "id",
	Type:           "type",
	UserId:         "user_id",
	OriginalAmount: "original_amount",
	PayAmount:      "pay_amount",
	Status:         "status",
	PayType:        "pay_type",
	Memo:           "memo",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
	DeletedAt:      "deleted_at",
	PayTime:        "pay_time",
	OrderNo:        "order_no",
}

// NewRechargeOrderDao creates and returns a new DAO object for table data access.
func NewRechargeOrderDao() *RechargeOrderDao {
	return &RechargeOrderDao{
		group:   "default",
		table:   "recharge_order",
		columns: rechargeOrderColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RechargeOrderDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *RechargeOrderDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *RechargeOrderDao) Columns() RechargeOrderColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *RechargeOrderDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RechargeOrderDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RechargeOrderDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
