// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SingleSubscriptionOrderDao is the data access object for table single_subscription_order.
type SingleSubscriptionOrderDao struct {
	table   string                         // table is the underlying table name of the DAO.
	group   string                         // group is the database configuration group name of current DAO.
	columns SingleSubscriptionOrderColumns // columns contains all the column names of Table for convenient usage.
}

// SingleSubscriptionOrderColumns defines and stores column names for table single_subscription_order.
type SingleSubscriptionOrderColumns struct {
	Id             string //
	Type           string //
	UserId         string //
	OriginalAmount string //
	PayAmount      string //
	Status         string //
	PayType        string //
	Memo           string //
	CreatedAt      string //
	UpdatedAt      string //
	DeletedAt      string //
	PayTime        string //
	OrderNo        string //
}

// singleSubscriptionOrderColumns holds the columns for table single_subscription_order.
var singleSubscriptionOrderColumns = SingleSubscriptionOrderColumns{
	Id:             "id",
	Type:           "type",
	UserId:         "user_id",
	OriginalAmount: "original_amount",
	PayAmount:      "pay_amount",
	Status:         "status",
	PayType:        "pay_type",
	Memo:           "memo",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
	DeletedAt:      "deleted_at",
	PayTime:        "pay_time",
	OrderNo:        "order_no",
}

// NewSingleSubscriptionOrderDao creates and returns a new DAO object for table data access.
func NewSingleSubscriptionOrderDao() *SingleSubscriptionOrderDao {
	return &SingleSubscriptionOrderDao{
		group:   "default",
		table:   "single_subscription_order",
		columns: singleSubscriptionOrderColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SingleSubscriptionOrderDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SingleSubscriptionOrderDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SingleSubscriptionOrderDao) Columns() SingleSubscriptionOrderColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SingleSubscriptionOrderDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SingleSubscriptionOrderDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SingleSubscriptionOrderDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
