// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// StatisticsDao is the data access object for table statistics.
type StatisticsDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns StatisticsColumns // columns contains all the column names of Table for convenient usage.
}

// StatisticsColumns defines and stores column names for table statistics.
type StatisticsColumns struct {
	Id           string //
	Knowledge    string // 知识下载总量
	Consultation string // 历史咨询人数
}

//  statisticsColumns holds the columns for table statistics.
var statisticsColumns = StatisticsColumns{
	Id:           "id",
	Knowledge:    "knowledge",
	Consultation: "consultation",
}

// NewStatisticsDao creates and returns a new DAO object for table data access.
func NewStatisticsDao() *StatisticsDao {
	return &StatisticsDao{
		group:   "default",
		table:   "statistics",
		columns: statisticsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *StatisticsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *StatisticsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *StatisticsDao) Columns() StatisticsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *StatisticsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *StatisticsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *StatisticsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
