// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// TycDao is the data access object for table tyc.
type TycDao struct {
	table   string     // table is the underlying table name of the DAO.
	group   string     // group is the database configuration group name of current DAO.
	columns TycColumns // columns contains all the column names of Table for convenient usage.
}

// TycColumns defines and stores column names for table tyc.
type TycColumns struct {
	Id        string //
	Name      string // 企业名称
	Type      string // 类型:commerce-工商信息,punishment-经营风险,qualification-资质,lawSuit-司法风险
	Number    string // 页吗
	Size      string // 页大小
	Body      string // 内容
	CreatedAt string // 创建日期
	UpdatedAt string // 修改日期
	DeletedAt string // 删除时间
}

//  tycColumns holds the columns for table tyc.
var tycColumns = TycColumns{
	Id:        "id",
	Name:      "name",
	Type:      "type",
	Number:    "number",
	Size:      "size",
	Body:      "body",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
}

// NewTycDao creates and returns a new DAO object for table data access.
func NewTycDao() *TycDao {
	return &TycDao{
		group:   "default",
		table:   "tyc",
		columns: tycColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *TycDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *TycDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *TycDao) Columns() TycColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *TycDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *TycDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *TycDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
