// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MemberSubscriptionDao is the data access object for table member_subscription.
type MemberSubscriptionDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns MemberSubscriptionColumns // columns contains all the column names of Table for convenient usage.
}

// MemberSubscriptionColumns defines and stores column names for table member_subscription.
type MemberSubscriptionColumns struct {
	Id                           string //
	MonthlycardSubscription      string // 月卡可订阅数
	QuartercardSubscription      string // 季卡可订阅数
	AnnualcardSubscription       string // 年卡可订阅数
	MonthlycardSubscriptionPrice string // 月卡新增订阅单价
	QuartercardSubscriptionPrice string // 季卡新增订阅单价
	AnnualcardSubscriptionPrice  string // 年卡新增订阅单价
}

//  memberSubscriptionColumns holds the columns for table member_subscription.
var memberSubscriptionColumns = MemberSubscriptionColumns{
	Id:                           "id",
	MonthlycardSubscription:      "monthlycard_subscription",
	QuartercardSubscription:      "quartercard_subscription",
	AnnualcardSubscription:       "annualcard_subscription",
	MonthlycardSubscriptionPrice: "monthlycard_subscription_price",
	QuartercardSubscriptionPrice: "quartercard_subscription_price",
	AnnualcardSubscriptionPrice:  "annualcard_subscription_price",
}

// NewMemberSubscriptionDao creates and returns a new DAO object for table data access.
func NewMemberSubscriptionDao() *MemberSubscriptionDao {
	return &MemberSubscriptionDao{
		group:   "default",
		table:   "member_subscription",
		columns: memberSubscriptionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MemberSubscriptionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MemberSubscriptionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MemberSubscriptionDao) Columns() MemberSubscriptionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MemberSubscriptionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MemberSubscriptionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MemberSubscriptionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
