// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PurchaseLogDao is the data access object for table purchase_log.
type PurchaseLogDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns PurchaseLogColumns // columns contains all the column names of Table for convenient usage.
}

// PurchaseLogColumns defines and stores column names for table purchase_log.
type PurchaseLogColumns struct {
	Id        string //
	NickName  string //
	Mobile    string //
	UserId    string //
	Memo      string //
	Amount    string //
	CreatedAt string //
	UpdatedAt string //
	DeletedAt string //
	TargetId  string //
	UserName  string //
	PayType   string // 支付类型
	OrderNo   string // 订单号
}

//  purchaseLogColumns holds the columns for table purchase_log.
var purchaseLogColumns = PurchaseLogColumns{
	Id:        "id",
	NickName:  "nick_name",
	Mobile:    "mobile",
	UserId:    "user_id",
	Memo:      "memo",
	Amount:    "amount",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	DeletedAt: "deleted_at",
	TargetId:  "target_id",
	UserName:  "user_name",
	PayType:   "pay_type",
	OrderNo:   "order_no",
}

// NewPurchaseLogDao creates and returns a new DAO object for table data access.
func NewPurchaseLogDao() *PurchaseLogDao {
	return &PurchaseLogDao{
		group:   "default",
		table:   "purchase_log",
		columns: purchaseLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PurchaseLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PurchaseLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PurchaseLogDao) Columns() PurchaseLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PurchaseLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PurchaseLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PurchaseLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
