// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysWxUserDao is the data access object for table sys_wx_user.
type SysWxUserDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns SysWxUserColumns // columns contains all the column names of Table for convenient usage.
}

// SysWxUserColumns defines and stores column names for table sys_wx_user.
type SysWxUserColumns struct {
	Id        string //
	MainId    string //
	OpenId    string //
	UnionId   string //
	CreatedAt string //
	UpdatedAt string //
}

// sysWxUserColumns holds the columns for table sys_wx_user.
var sysWxUserColumns = SysWxUserColumns{
	Id:        "id",
	MainId:    "main_id",
	OpenId:    "open_id",
	UnionId:   "union_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewSysWxUserDao creates and returns a new DAO object for table data access.
func NewSysWxUserDao() *SysWxUserDao {
	return &SysWxUserDao{
		group:   "default",
		table:   "sys_wx_user",
		columns: sysWxUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysWxUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysWxUserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysWxUserDao) Columns() SysWxUserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysWxUserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysWxUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysWxUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
