// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysWsMsgDao is the data access object for table sys_ws_msg.
type SysWsMsgDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns SysWsMsgColumns // columns contains all the column names of Table for convenient usage.
}

// SysWsMsgColumns defines and stores column names for table sys_ws_msg.
type SysWsMsgColumns struct {
	Id        string //
	MessageId string //
	UserId    string //
	Content   string //
	IsRead    string //
	IsDel     string //
	CreatedAt string //
	UpdatedAt string //
}

// sysWsMsgColumns holds the columns for table sys_ws_msg.
var sysWsMsgColumns = SysWsMsgColumns{
	Id:        "id",
	MessageId: "message_id",
	UserId:    "user_id",
	Content:   "content",
	IsRead:    "is_read",
	IsDel:     "is_del",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewSysWsMsgDao creates and returns a new DAO object for table data access.
func NewSysWsMsgDao() *SysWsMsgDao {
	return &SysWsMsgDao{
		group:   "default",
		table:   "sys_ws_msg",
		columns: sysWsMsgColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysWsMsgDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysWsMsgDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysWsMsgDao) Columns() SysWsMsgColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysWsMsgDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysWsMsgDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysWsMsgDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
