// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Consultation is the golang structure for table consultation.
type Consultation struct {
	Id           uint64      `json:"id"           description:""`
	Type         string      `json:"type"         description:"类型"`
	Title        string      `json:"title"        description:"标题"`
	Content      string      `json:"content"      description:"内容"`
	Publish      string      `json:"publish"      description:"发布日期"`
	Expiry       string      `json:"expiry"       description:"施行日期"`
	Office       string      `json:"office"       description:"制定机关"`
	Url          string      `json:"url"          description:"外部链接"`
	Attachment   string      `json:"attachment"   description:"附件"`
	CreatedAt    *gtime.Time `json:"createdAt"    description:"创建时间"`
	Source       string      `json:"source"       description:"来源"`
	Status       uint        `json:"status"       description:"0 无效,1 有效 时效性"`
	Display      uint        `json:"display"      description:"是否展示,0不展示1展示"`
	Height       string      `json:"height"       description:"0高1中2低"`
	Rank         string      `json:"rank"         description:"排序"`
	Site         string      `json:"site"         description:"来源"`
	OriginalType string      `json:"originalType" description:"原始类型"`
	Crawler      uint        `json:"crawler"      description:"是否爬取,0 非爬取 1 爬取"`
}
