// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Feedback is the golang structure for table feedback.
type Feedback struct {
	Id                 uint64      `json:"id"                 description:""`
	BulletinId         uint64      `json:"bulletinId"         description:"关联公告id"`
	Company            string      `json:"company"            description:"公司名称"`
	ContactPerson      string      `json:"contactPerson"      description:"联系人"`
	ContactInformation string      `json:"contactInformation" description:"联系方式"`
	ReleaseTime        string      `json:"releaseTime"        description:"发布时间"`
	Remarks            string      `json:"remarks"            description:"备注"`
	Attachment         string      `json:"attachment"         description:"附件"`
	Reject             string      `json:"reject"             description:"驳回留言"`
	Status             uint        `json:"status"             description:"反馈状态;0:待审核,1:通过，2:驳回"`
	CreatedAt          *gtime.Time `json:"createdAt"          description:"爬取日期"`
	UserId             int64       `json:"userId"             description:"用户id"`
	UserName           string      `json:"userName"           description:"用户名"`
}
