// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// HisKnowledge is the golang structure for table his_knowledge.
type HisKnowledge struct {
	Id          uint64      `json:"id"          description:""`
	KnowledgeId int64       `json:"knowledgeId" description:"知识id"`
	UserId      int64       `json:"userId"      description:"用户id"`
	CreatedAt   *gtime.Time `json:"createdAt"   description:"发布时间"`
	UpdatedAt   *gtime.Time `json:"updatedAt"   description:"更新时间"`
	DeletedAt   *gtime.Time `json:"deletedAt"   description:"删除时间"`
}
