// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Law is the golang structure for table law.
type Law struct {
	Id         int64  `json:"id"         description:"UID"`
	Fileid     string `json:"fileid"     description:"文件id"`
	Publish    string `json:"publish"    description:"公布日期"`
	Expiry     string `json:"expiry"     description:"施行日期"`
	Office     string `json:"office"     description:"制定机关"`
	Title      string `json:"title"      description:"标题"`
	Type       string `json:"type"       description:"类型"`
	Word       string `json:"word"       description:"word"`
	Pdf        string `json:"pdf"        description:"pdf"`
	Url        string `json:"url"        description:"外部链接"`
	Status     uint   `json:"status"     description:"0 无效,1 有效 时效性"`
	Display    uint   `json:"display"    description:"是否展示,0不展示1展示"`
	Content    string `json:"content"    description:"内容"`
	Level      string `json:"level"      description:"法律效力位阶"`
	Attachment string `json:"attachment" description:"附件"`
	Height     string `json:"height"     description:"0高1中2低"`
	Rank       string `json:"rank"       description:"排序"`
	Crawler    uint   `json:"crawler"    description:"是否爬取,0 非爬取 1 爬取"`
}
