// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MemberKnowledge is the golang structure for table member_knowledge.
type MemberKnowledge struct {
	Id                      uint64      `json:"id"                      description:""`
	Title                   string      `json:"title"                   description:"标题"`
	KnowledgeType           string      `json:"knowledgeType"           description:"知识类型"`
	Authority               uint        `json:"authority"               description:"阅读下载权限，0:所有,1:会员"`
	PrimaryClassification   string      `json:"primaryClassification"   description:"一级分类"`
	SecondaryClassification string      `json:"secondaryClassification" description:"二级分类"`
	IntegralSetting         int         `json:"integralSetting"         description:"积分设置"`
	Content                 string      `json:"content"                 description:"内容"`
	ReviewMessage           string      `json:"reviewMessage"           description:"审核留言"`
	ReviewStatus            uint        `json:"reviewStatus"            description:"审核状态;0:待审核,1:通过，2:未通过"`
	UserId                  int64       `json:"userId"                  description:"发布作者"`
	CreatedAt               *gtime.Time `json:"createdAt"               description:"发布时间"`
	UpdatedAt               *gtime.Time `json:"updatedAt"               description:"更新时间"`
	DeletedAt               *gtime.Time `json:"deletedAt"               description:"删除时间"`
	UserName                string      `json:"userName"                description:"发布作者"`
	Type                    uint        `json:"type"                    description:"0:其他,1:视频"`
	CoverUrl                string      `json:"coverUrl"                description:"封面主图"`
	DetailsUrl              string      `json:"detailsUrl"              description:"详情主图"`
	VideoUrl                string      `json:"videoUrl"                description:"视频链接"`
	VideoIntroduction       string      `json:"videoIntroduction"       description:"视频简介"`
	Views                   int         `json:"views"                   description:"浏览量"`
	AttachmentUrl           string      `json:"attachmentUrl"           description:"附件链接"`
	OpreviewMessage         string      `json:"opreviewMessage"         description:"管理员留言"`
	IsAdmin                 int         `json:"isAdmin"                 description:"是否后台管理员 1 是  0 否"`
	ShortvideoUrl           string      `json:"shortvideoUrl"           description:"视频链接"`
	Abstract                string      `json:"abstract"                description:"摘要"`
	Display                 uint        `json:"display"                 description:"是否展示,0不展示1展示"`
	Height                  string      `json:"height"                  description:"0高1中2低"`
	Rank                    string      `json:"rank"                    description:"排序"`
	Site                    string      `json:"site"                    description:"站点"`
	OriginalType            string      `json:"originalType"            description:"原始类型"`
	Url                     string      `json:"url"                     description:"外部链接"`
	CutStatus               uint        `json:"cutStatus"               description:"是否展示,0进行中 1 已完成"`
	Crawler                 uint        `json:"crawler"                 description:"是否爬取,0 非爬取 1 爬取"`
}
