// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MemberSubscription is the golang structure for table member_subscription.
type MemberSubscription struct {
	Id                           uint64 `json:"id"                           description:""`
	MonthlycardSubscription      int    `json:"monthlycardSubscription"      description:"月卡可订阅数"`
	QuartercardSubscription      int    `json:"quartercardSubscription"      description:"季卡可订阅数"`
	AnnualcardSubscription       int    `json:"annualcardSubscription"       description:"年卡可订阅数"`
	MonthlycardSubscriptionPrice string `json:"monthlycardSubscriptionPrice" description:"月卡新增订阅单价"`
	QuartercardSubscriptionPrice string `json:"quartercardSubscriptionPrice" description:"季卡新增订阅单价"`
	AnnualcardSubscriptionPrice  string `json:"annualcardSubscriptionPrice"  description:"年卡新增订阅单价"`
}
