// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// MemberSubscribe is the golang structure for table member_subscribe.
type MemberSubscribe struct {
	Id        uint64      `json:"id"        description:""`
	Name      string      `json:"name"      description:"方案名称"`
	Type      string      `json:"type"      description:"信息类型"`
	Location  string      `json:"location"  description:"所在地"`
	Keywords  string      `json:"keywords"  description:"关键字"`
	UserId    int         `json:"userId"    description:"用户id"`
	CreatedAt *gtime.Time `json:"createdAt" description:"收藏时间"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
	Industry  string      `json:"industry"  description:"行业类型"`
}
