// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Statistics is the golang structure for table statistics.
type Statistics struct {
	Id           uint64 `json:"id"           description:""`
	Knowledge    int    `json:"knowledge"    description:"知识下载总量"`
	Consultation int    `json:"consultation" description:"历史咨询人数"`
}
