// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Tyc is the golang structure for table tyc.
type Tyc struct {
	Id        uint        `json:"id"        description:""`
	Name      string      `json:"name"      description:"企业名称"`
	Type      string      `json:"type"      description:"类型:commerce-工商信息,punishment-经营风险,qualification-资质,lawSuit-司法风险"`
	Number    uint        `json:"number"    description:"页吗"`
	Size      uint        `json:"size"      description:"页大小"`
	Body      string      `json:"body"      description:"内容"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建日期"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"修改日期"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
