// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "tender/internal/app/common/logic/cache"
	_ "tender/internal/app/common/logic/middleware"
)
