package logic

import _ "tender/internal/app/desk/logic/user"
import _ "tender/internal/app/desk/logic/token"
import _ "tender/internal/app/desk/logic/context"
import _ "tender/internal/app/desk/logic/publish"
import _ "tender/internal/app/desk/logic/middleware"
import _ "tender/internal/app/desk/logic/tenderdata"
import _ "tender/internal/app/desk/logic/viporder"
import _ "tender/internal/app/desk/logic/knowledgeorder"
import _ "tender/internal/app/desk/logic/rechargeorder"
import _ "tender/internal/app/desk/logic/singlesubscriptionorder"
import _ "tender/internal/app/desk/logic/collect"
import _ "tender/internal/app/desk/logic/index"
import _ "tender/internal/app/desk/logic/bbs"
