// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalBbsLikeDao is internal type for wrapping internal DAO implements.
type internalBbsLikeDao = *internal.BbsLikeDao

// bbsLikeDao is the data access object for table bbs_like.
// You can define custom methods on it to extend its functionality as you wish.
type bbsLikeDao struct {
	internalBbsLikeDao
}

var (
	// BbsLike is globally public accessible object for table bbs_like operations.
	BbsLike = bbsLikeDao{
		internal.NewBbsLikeDao(),
	}
)

// Fill with you ideas below.
