// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalBbsReplyDao is internal type for wrapping internal DAO implements.
type internalBbsReplyDao = *internal.BbsReplyDao

// bbsReplyDao is the data access object for table bbs_reply.
// You can define custom methods on it to extend its functionality as you wish.
type bbsReplyDao struct {
	internalBbsReplyDao
}

var (
	// BbsReply is globally public accessible object for table bbs_reply operations.
	BbsReply = bbsReplyDao{
		internal.NewBbsReplyDao(),
	}
)

// Fill with you ideas below.
