// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalBbsContentDao is internal type for wrapping internal DAO implements.
type internalBbsContentDao = *internal.BbsContentDao

// bbsContentDao is the data access object for table bbs_content.
// You can define custom methods on it to extend its functionality as you wish.
type bbsContentDao struct {
	internalBbsContentDao
}

var (
	// BbsContent is globally public accessible object for table bbs_content operations.
	BbsContent = bbsContentDao{
		internal.NewBbsContentDao(),
	}
)

// Fill with you ideas below.
