// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalBidDao is internal type for wrapping internal DAO implements.
type internalBidDao = *internal.BidDao

// bidDao is the data access object for table bid.
// You can define custom methods on it to extend its functionality as you wish.
type bidDao struct {
	internalBidDao
}

var (
	// Bid is globally public accessible object for table bid operations.
	Bid = bidDao{
		internal.NewBidDao(),
	}
)

// Fill with you ideas below.
