// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalConsultationDao is internal type for wrapping internal DAO implements.
type internalConsultationDao = *internal.ConsultationDao

// consultationDao is the data access object for table consultation.
// You can define custom methods on it to extend its functionality as you wish.
type consultationDao struct {
	internalConsultationDao
}

var (
	// Consultation is globally public accessible object for table consultation operations.
	Consultation = consultationDao{
		internal.NewConsultationDao(),
	}
)

// Fill with you ideas below.
