// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalHisKnowledgeDao is internal type for wrapping internal DAO implements.
type internalHisKnowledgeDao = *internal.HisKnowledgeDao

// hisKnowledgeDao is the data access object for table his_knowledge.
// You can define custom methods on it to extend its functionality as you wish.
type hisKnowledgeDao struct {
	internalHisKnowledgeDao
}

var (
	// HisKnowledge is globally public accessible object for table his_knowledge operations.
	HisKnowledge = hisKnowledgeDao{
		internal.NewHisKnowledgeDao(),
	}
)

// Fill with you ideas below.
