// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalKnowledgeOrderDao is internal type for wrapping internal DAO implements.
type internalKnowledgeOrderDao = *internal.KnowledgeOrderDao

// knowledgeOrderDao is the data access object for table knowledge_order.
// You can define custom methods on it to extend its functionality as you wish.
type knowledgeOrderDao struct {
	internalKnowledgeOrderDao
}

var (
	// KnowledgeOrder is globally public accessible object for table knowledge_order operations.
	KnowledgeOrder = knowledgeOrderDao{
		internal.NewKnowledgeOrderDao(),
	}
)

// Fill with you ideas below.
