// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalLawDao is internal type for wrapping internal DAO implements.
type internalLawDao = *internal.LawDao

// lawDao is the data access object for table law.
// You can define custom methods on it to extend its functionality as you wish.
type lawDao struct {
	internalLawDao
}

var (
	// Law is globally public accessible object for table law operations.
	Law = lawDao{
		internal.NewLawDao(),
	}
)

// Fill with you ideas below.
