// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalMemberSubscriptionDao is internal type for wrapping internal DAO implements.
type internalMemberSubscriptionDao = *internal.MemberSubscriptionDao

// memberSubscriptionDao is the data access object for table member_subscription.
// You can define custom methods on it to extend its functionality as you wish.
type memberSubscriptionDao struct {
	internalMemberSubscriptionDao
}

var (
	// MemberSubscription is globally public accessible object for table member_subscription operations.
	MemberSubscription = memberSubscriptionDao{
		internal.NewMemberSubscriptionDao(),
	}
)

// Fill with you ideas below.
