// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalMemberCollectDao is internal type for wrapping internal DAO implements.
type internalMemberCollectDao = *internal.MemberCollectDao

// memberCollectDao is the data access object for table member_collect.
// You can define custom methods on it to extend its functionality as you wish.
type memberCollectDao struct {
	internalMemberCollectDao
}

var (
	// MemberCollect is globally public accessible object for table member_collect operations.
	MemberCollect = memberCollectDao{
		internal.NewMemberCollectDao(),
	}
)

// Fill with you ideas below.
