// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalMemberKnowledgeDao is internal type for wrapping internal DAO implements.
type internalMemberKnowledgeDao = *internal.MemberKnowledgeDao

// memberKnowledgeDao is the data access object for table member_knowledge.
// You can define custom methods on it to extend its functionality as you wish.
type memberKnowledgeDao struct {
	internalMemberKnowledgeDao
}

var (
	// MemberKnowledge is globally public accessible object for table member_knowledge operations.
	MemberKnowledge = memberKnowledgeDao{
		internal.NewMemberKnowledgeDao(),
	}
)

// Fill with you ideas below.
