// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalMemberSubscribeDao is internal type for wrapping internal DAO implements.
type internalMemberSubscribeDao = *internal.MemberSubscribeDao

// memberSubscribeDao is the data access object for table member_subscribe.
// You can define custom methods on it to extend its functionality as you wish.
type memberSubscribeDao struct {
	internalMemberSubscribeDao
}

var (
	// MemberSubscribe is globally public accessible object for table member_subscribe operations.
	MemberSubscribe = memberSubscribeDao{
		internal.NewMemberSubscribeDao(),
	}
)

// Fill with you ideas below.
