// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalRechargeOrderDao is internal type for wrapping internal DAO implements.
type internalRechargeOrderDao = *internal.RechargeOrderDao

// rechargeOrderDao is the data access object for table recharge_order.
// You can define custom methods on it to extend its functionality as you wish.
type rechargeOrderDao struct {
	internalRechargeOrderDao
}

var (
	// RechargeOrder is globally public accessible object for table recharge_order operations.
	RechargeOrder = rechargeOrderDao{
		internal.NewRechargeOrderDao(),
	}
)

// Fill with you ideas below.
