// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalSingleSubscriptionOrderDao is internal type for wrapping internal DAO implements.
type internalSingleSubscriptionOrderDao = *internal.SingleSubscriptionOrderDao

// singleSubscriptionOrderDao is the data access object for table single_subscription_order.
// You can define custom methods on it to extend its functionality as you wish.
type singleSubscriptionOrderDao struct {
	internalSingleSubscriptionOrderDao
}

var (
	// SingleSubscriptionOrder is globally public accessible object for table single_subscription_order operations.
	SingleSubscriptionOrder = singleSubscriptionOrderDao{
		internal.NewSingleSubscriptionOrderDao(),
	}
)

// Fill with you ideas below.
