// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalStatisticsDao is internal type for wrapping internal DAO implements.
type internalStatisticsDao = *internal.StatisticsDao

// statisticsDao is the data access object for table statistics.
// You can define custom methods on it to extend its functionality as you wish.
type statisticsDao struct {
	internalStatisticsDao
}

var (
	// Statistics is globally public accessible object for table statistics operations.
	Statistics = statisticsDao{
		internal.NewStatisticsDao(),
	}
)

// Fill with you ideas below.
