// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalTycDao is internal type for wrapping internal DAO implements.
type internalTycDao = *internal.TycDao

// tycDao is the data access object for table tyc.
// You can define custom methods on it to extend its functionality as you wish.
type tycDao struct {
	internalTycDao
}

var (
	// Tyc is globally public accessible object for table tyc operations.
	Tyc = tycDao{
		internal.NewTycDao(),
	}
)

// Fill with you ideas below.
