// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"tender/internal/app/desk/dao/internal"
)

// internalVipOrderDao is internal type for wrapping internal DAO implements.
type internalVipOrderDao = *internal.VipOrderDao

// vipOrderDao is the data access object for table vip_order.
// You can define custom methods on it to extend its functionality as you wish.
type vipOrderDao struct {
	internalVipOrderDao
}

var (
	// VipOrder is globally public accessible object for table vip_order operations.
	VipOrder = vipOrderDao{
		internal.NewVipOrderDao(),
	}
)

// Fill with you ideas below.
