// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BbsReply is the golang structure of table bbs_reply for DAO operations like Where/Data.
type BbsReply struct {
	g.Meta    `orm:"table:bbs_reply, do:true"`
	Id        interface{} //
	BbsId     interface{} // 论坛id
	ReplyId   interface{} // 回复id
	Content   interface{} // 回复内容
	LikeCount interface{} // 点赞量
	UserId    interface{} // 用户id
	CreatedAt *gtime.Time // 发布时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
