// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// BbsContent is the golang structure of table bbs_content for DAO operations like Where/Data.
type BbsContent struct {
	g.Meta  `orm:"table:bbs_content, do:true"`
	Id      interface{} //
	BbsId   interface{} // 论坛id
	Content interface{} // 内容
}
