// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Bid is the golang structure of table bid for DAO operations like Where/Data.
type Bid struct {
	g.Meta                 `orm:"table:bid, do:true"`
	Id                     interface{} //
	BulletinType           interface{} // 公告类型
	OriginalType           interface{} // 原公告类型
	Province               interface{} // 所属省份
	City                   interface{} // 所属城市
	IndustryClassification interface{} // 行业分类
	OriginalClassification interface{} // 原行业分类
	ReleaseTime            interface{} // 发布时间
	BidopeningTime         interface{} // 开标时间
	Title                  interface{} // 标题
	Abstract               interface{} // 摘要
	AnnouncementContent    interface{} // 公告内容
	OriginalContent        interface{} // 未清洗的公告内容
	Link                   interface{} // 源链接
	OriginalLink           interface{} // 源源链接
	Attachment             interface{} // 招标附件
	Amount                 interface{} // 金额
	ContactPerson          interface{} // 联系人
	ContactInformation     interface{} // 联系方式
	BidAmount              interface{} // 中标金额
	TenderName             interface{} // 招标企业
	WinName                interface{} // 中标企业
	Site                   interface{} // 站点
	CreatedAt              *gtime.Time // 爬取日期
	Height                 interface{} // 1高2中3低
	Rank                   interface{} // 排序
	Area                   interface{} // 地区排序
	Display                interface{} // 是否展示,0不展示1展示
	Crawler                interface{} // 是否爬取,0 非爬取 1 爬取
	ReleaseDay             interface{} // 发布时间day排序用的
}
