// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Bidding is the golang structure of table bidding for DAO operations like Where/Data.
type Bidding struct {
	g.Meta                 `orm:"table:bidding, do:true"`
	Id                     interface{} //
	BulletinType           interface{} // 公告类型
	City                   interface{} // 所属城市
	IndustryClassification interface{} // 行业分类
	ReleaseTime            interface{} // 发布时间
	BidopeningTime         interface{} // 开标时间
	Title                  interface{} // 标题
	Abstract               interface{} // 摘要
	Enterprise             interface{} // 企业信息
	AnnouncementContent    interface{} // 公告内容
	Link                   interface{} // 源链接
	Attachment             interface{} // 招标附件
	Amount                 interface{} // 金额
	ContactPerson          interface{} // 联系人
	ContactInformation     interface{} // 联系方式
	CreatedAt              *gtime.Time // 爬取日期
	BidAmount              interface{} // 中标金额
	TenderName             interface{} // 招标企业
	WinName                interface{} // 中标企业
}
