// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Consultation is the golang structure of table consultation for DAO operations like Where/Data.
type Consultation struct {
	g.Meta       `orm:"table:consultation, do:true"`
	Id           interface{} //
	Type         interface{} // 类型
	Title        interface{} // 标题
	Content      interface{} // 内容
	Publish      interface{} // 发布日期
	Expiry       interface{} // 施行日期
	Office       interface{} // 制定机关
	Url          interface{} // 外部链接
	Attachment   interface{} // 附件
	CreatedAt    *gtime.Time // 创建时间
	Source       interface{} // 来源
	Status       interface{} // 0 无效,1 有效 时效性
	Display      interface{} // 是否展示,0不展示1展示
	Height       interface{} // 0高1中2低
	Rank         interface{} // 排序
	Site         interface{} // 来源
	OriginalType interface{} // 原始类型
	Crawler      interface{} // 是否爬取,0 非爬取 1 爬取
}
