// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Feedback is the golang structure of table feedback for DAO operations like Where/Data.
type Feedback struct {
	g.Meta             `orm:"table:feedback, do:true"`
	Id                 interface{} //
	BulletinId         interface{} // 关联公告id
	Company            interface{} // 公司名称
	ContactPerson      interface{} // 联系人
	ContactInformation interface{} // 联系方式
	ReleaseTime        interface{} // 发布时间
	Remarks            interface{} // 备注
	Attachment         interface{} // 附件
	Reject             interface{} // 驳回留言
	Status             interface{} // 反馈状态;0:待审核,1:通过，2:驳回
	CreatedAt          *gtime.Time // 爬取日期
	UserId             interface{} // 用户id
	UserName           interface{} // 用户名
}
