// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// KnowledgeOrder is the golang structure of table knowledge_order for DAO operations like Where/Data.
type KnowledgeOrder struct {
	g.Meta         `orm:"table:knowledge_order, do:true"`
	Id             interface{} //
	Type           interface{} //
	UserId         interface{} //
	OriginalAmount interface{} //
	PayAmount      interface{} //
	Status         interface{} //
	PayType        interface{} //
	Memo           interface{} //
	CreatedAt      *gtime.Time //
	UpdatedAt      *gtime.Time //
	DeletedAt      *gtime.Time //
	PayTime        interface{} //
	OrderNo        interface{} //
	KnowledgeId    interface{} //
}
