// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MemberSubscription is the golang structure of table member_subscription for DAO operations like Where/Data.
type MemberSubscription struct {
	g.Meta                       `orm:"table:member_subscription, do:true"`
	Id                           interface{} //
	MonthlycardSubscription      interface{} // 月卡可订阅数
	QuartercardSubscription      interface{} // 季卡可订阅数
	AnnualcardSubscription       interface{} // 年卡可订阅数
	MonthlycardSubscriptionPrice interface{} // 月卡新增订阅单价
	QuartercardSubscriptionPrice interface{} // 季卡新增订阅单价
	AnnualcardSubscriptionPrice  interface{} // 年卡新增订阅单价
}
