// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MemberFee is the golang structure of table member_fee for DAO operations like Where/Data.
type MemberFee struct {
	g.Meta              `orm:"table:member_fee, do:true"`
	Id                  interface{} //
	MonthlycardOriginal interface{} // 月卡原价
	MonthlycardCurrent  interface{} // 月卡现价
	QuartercardOriginal interface{} // 季卡原价
	QuartercardCurrent  interface{} // 季卡现价
	AnnualcardOriginal  interface{} // 年卡原价
	AnnualcardCurrent   interface{} // 年卡现价
	DownloadKnowledge   interface{} // 下载知识
	DownloadVideo       interface{} // 下载视频
}
