// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MemberSubscribe is the golang structure of table member_subscribe for DAO operations like Where/Data.
type MemberSubscribe struct {
	g.Meta    `orm:"table:member_subscribe, do:true"`
	Id        interface{} //
	Name      interface{} // 方案名称
	Type      interface{} // 信息类型
	Location  interface{} // 所在地
	Keywords  interface{} // 关键字
	UserId    interface{} // 用户id
	CreatedAt *gtime.Time // 收藏时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
	Industry  interface{} // 行业类型
}
