// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// MemberCollect is the golang structure of table member_collect for DAO operations like Where/Data.
type MemberCollect struct {
	g.Meta    `orm:"table:member_collect, do:true"`
	Id        interface{} //
	Title     interface{} // 标题
	Type      interface{} // 类型
	Location  interface{} // 所在地
	Industry  interface{} // 行业
	UserId    interface{} // 用户id
	ArticleId interface{} // 文章id
	CreatedAt *gtime.Time // 收藏时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
	Url       interface{} // 收藏url
}
