// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Statistics is the golang structure of table statistics for DAO operations like Where/Data.
type Statistics struct {
	g.Meta       `orm:"table:statistics, do:true"`
	Id           interface{} //
	Knowledge    interface{} // 知识下载总量
	Consultation interface{} // 历史咨询人数
}
